services:
  postgres:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_PASSWORD: gizlisifrem
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: redis
    container_name: redis-cache
    ports:
      - "6379:6379"
