spring.application.name=KutuphaneOtomasyon

security.jwt.secret-key=WTVEipQRErKljElSOBEyX7ZgKK+qTZz3eA3wKHvp4xA=
security.jwt.expiration-time=86400000
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=gizlisifrem

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=kutuphaneotomasyon
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail ayarlar?
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sumeyyeberfinkorkmaz@gmail.com
spring.mail.password=qievqyymacluesai
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.security=DEBUG
