spring.application.name=KutuphaneOtomasyon

security.jwt.secret-key=WTVEipQRErKljElSOBEyX7ZgKK+qTZz3eA3wKHvp4xA=
security.jwt.expiration-time=86400000
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=gizlisifrem

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=kutuphaneotomasyon
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

admin.seed.username=admin
admin.seed.password=admin123
admin.seed.email=admin@kutuphane.com

logging.level.org.springframework.security=DEBUG
